### ISSUE TITLE
clarify libfabric dependency

### ISSUE THREAD

**Issue by carns** [mercury-hpc/fabtsuite#15]
On the ALCF Polaris system, a Spack build of fabtsuite fails with the following error:

```
1 error found in build log:
     18    -- Detecting CXX compile features - done
     19    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
     20    -- Checking for module 'libfabric>=1.13'
     21    --   Requested 'libfabric >= 1.13' but version of libfabric is 1.11.
           0.4.125
     22    You may find new versions of libfabric at https://github.com/ofiwg/l
           ibfabric.git
     23    -- Could NOT find LIBFABRIC (missing: LIBFABRIC_LIBRARIES)
  >> 24    CMake Error at cmake/FindLIBFABRIC.cmake:69 (message):
     25      Could not find a suitable version of libfabric (>=1.13)
     26    Call Stack (most recent call first):
     27      CMakeLists.txt:8 (include) 
```

What exact features from 1.13 does the test suite require?  It may be that they are actually present in this build even though it is reporting a version number less than 1.13 (the version may not track exactly in a vendor-provided library).

For reference, Mercury itself will build fine against this same version of libfabric, so hopefully it's not a particularly strict dependency.

**Comment by hyoklee** [comment]
@gnuoyd , can  you answer this? I don't know why v. > 1.13 is strictly required.

**Comment by carns** [comment]
Here is the spack environment file that I am using to test against the platform default libfabric on Polaris is pasted below.

To use it, do something like:
```
# save listing as fabtsuite-polaris.yaml
# edit the repos: entry to point to the directory where your copy of mochi-spack-packages is
> spack env create fabtsuite-polaris fabtsuite-polaris.yaml
> spack env activate fabtsuite-polaris
# this final step will fail due to the dependency check on libfabric in cmake
> spack install
```

```
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
  - fabtsuite ^libfabric@1.11.0.4.125
  view: true
  repos:
  - /home/carns/working/src/mochi/mochi-spack-packages
  modules:
    prefix_inspections:
      lib: [LD_LIBRARY_PATH]
      lib64: [LD_LIBRARY_PATH]
  compilers:
  - compiler:
      spec: gcc@11.2.0
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: sles15
      target: any
      modules:
      - PrgEnv-gnu
      - gcc/11.2.0
      - libfabric
      - cudatoolkit-standalone
      environment: {}
      extra_rpaths: []
  packages:
    all:
      providers:
        mpi: [ cray-mpich ]
      compiler:
      - gcc@11.2.0
      target:
      - zen3
      version: []
      buildable: true
    cray-mpich:
      buildable: false
      version: []
      target: []
      compiler: []
      providers: {}
      externals:
      - spec: cray-mpich@8.1.16 arch=cray-sles15-zen3
        modules:
        - cray-mpich/8.1.16
    mercury:
      variants: ~boostsys ~checksum
      buildable: true
      version: []
      target: []
      providers: {}
      compiler: []
    libfabric:
      externals:
      - spec: libfabric@1.11.0.4.125
        modules:
        - libfabric/1.11.0.4.125
      buildable: true
      version: []
      target: []
      providers: {}
      compiler: []
    autoconf:
      buildable: false
      version: []
      target: []
      compiler: []
      providers: {}
      externals:
      - spec: autoconf@2.69
        prefix: /usr
    automake:
      buildable: false
      version: []
      target: []
      compiler: []
      providers: {}
      externals:
      - spec: automake@1.15.1
        prefix: /usr
    cmake:
      buildable: false
      version: []
      target: []
      compiler: []
      providers: {}
      externals:
      - spec: cmake@3.23.2
        modules:
        - cmake/3.23.2
    libtool:
      buildable: false
      version: []
      target: []
      compiler: []
      providers: {}
      externals:
      - spec: libtool@2.4.6
        prefix: /usr
    openssl:
      buildable: false
      version: []
      target: []
      compiler: []
      providers: {}
      externals:
      - spec: openssl@1.1.1d
        prefix: /usr
    m4:
      externals:
      - spec: m4@1.4.18
        prefix: /usr
```
